{% set name = "vector-quantize-pytorch" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lucidrains/{{ name }}/archive/{{ version }}.tar.gz
  sha256: c86a56c91c43b5a37da4182f86f6141fec2be39568ed41a5d3840e6316e3b0a7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pytorch

test:
  imports:
    - vector_quantize_pytorch

about:
  home: https://github.com/lucidrains/vector-quantizer-pytorch
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple Vector Quantization, in Pytorch
  dev_url: https://github.com/lucidrains/vector-quantizer-pytorch

extra:
  recipe-maintainers:
    - psortos
    - oblute
    - mxr-conda
