{% set name = "vector-quantize-pytorch" %}
{% set version = "1.22.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vector_quantize_pytorch-{{ version }}.tar.gz
  sha256: 284e6c1a676862ac364c38319c956cc02f93155f0d906f95d8ba567ff7b65721

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ={{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - pytorch >=2.0
    - einops >=0.8.0
    - einx >=0.3.0

test:
  imports:
    - vector_quantize_pytorch
  commands:
    - pip check
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://github.com/lucidrains/vector-quantize-pytorch
  summary: Vector Quantization - Pytorch
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
